docs: first draft of readme
DevOps-2023-TeamA/tsao-frontend-svc pull request #15
Opened 2024-01-15 04:50 UTC by Kuan-Zher

2024-01-15 04:57 UTC, DevOps-2023-TeamA submitted a review, later dismissed
Approved.

2024-01-15 05:01 UTC, DanielCheahSJ approved these changes
Approved.

2024-01-15 07:38 UTC, jiachenyee requested changes

2024-01-15 07:38 UTC, jiachenyee commented on README.md
> +## Maintainers
Should we put our student IDs?

2024-01-15 07:38 UTC, jiachenyee commented on README.md
> +## Maintainers
cc: @isabellepakyishan

2024-01-29 12:35 UTC, jiachenyee approved these changes
Thanks for the change, lgtm!

2024-01-29 12:35 UTC, merged