feat/account
DevOps-2023-TeamA/tsao-frontend-svc pull request #24
Opened 2024-02-04 23:32 UTC by isabellepakyishan

Admin/User - Add new account: Closes #2 
Admin - Account Management: Closes #7 
Admin - Update account information + Approve account + Modify account password: Closes #9 
Admin - Delete account: Closes #8

2024-02-04 23:38 UTC, jiachenyee requested changes
Are we changing the page titles?

2024-02-04 23:38 UTC, jiachenyee commented on accounts-management.html
> +    <title>Home | TSA0 Records Systems</title>
Aren't we changing the title line?

2024-02-04 23:38 UTC, jiachenyee commented on change-password.html
> +        <title>Home | TSAO Capstone Records System</title>
Also page title

2024-02-04 23:54 UTC, Kuan-Zher requested changes
Change the titles to the correct title

2024-02-04 23:54 UTC, Kuan-Zher commented on accounts-management.html
> +    <title>Home | TSA0 Records Systems</title>
Title should be "TSA Office Records Systems"

2024-02-04 23:54 UTC, Kuan-Zher commented on change-password.html
> +        <title>Home | TSAO Capstone Records System</title>
Title should be "TSA Office Records Systems"

2024-02-05 00:07 UTC, jiachenyee approved these changes
thanks for the change! looks good!

2024-02-05 00:08 UTC, Kuan-Zher approved these changes
Lgtm

2024-02-05 00:09 UTC, merged